[package]
name = "aster-axvisor-host"
version = "0.1.0"
edition.workspace = true

[features]
default = []
vmx = ["axvisor_core/vmx"]
sstc = ["axvisor_core/sstc"]

[dependencies]
aster-console.workspace = true
aster-logger.workspace = true
aster-time.workspace = true
ax-percpu = { git = "https://github.com/Ivans-11/tgoskits", branch = "axvisor-core", features = ["custom-base"] }
ax-errno = { git = "https://github.com/Ivans-11/tgoskits", branch = "axvisor-core" }
axvisor_api = { git = "https://github.com/Ivans-11/tgoskits", branch = "axvisor-core" }
axvisor_core = { git = "https://github.com/Ivans-11/tgoskits", branch = "axvisor-core" }
ostd.workspace = true
spin.workspace = true

[lints]
workspace = true
