[package]
name = "aster-axvisor-host"
version = "0.1.0"
edition.workspace = true

[features]
default = []
control = ["axvisor_api/control", "axvisor_core/control"]
shell = ["axvisor_api/shell", "axvisor_core/shell"]
vmx = ["axvisor_core/vmx"]
svm = ["axvisor_core/svm"]
sstc = ["axvisor_core/sstc"]

[dependencies]
aster-console.workspace = true
aster-logger.workspace = true
aster-time.workspace = true
ax-errno = { git = "https://github.com/Ivans-11/tgoskits", branch = "axvisor-core" }
ax-percpu = { git = "https://github.com/Ivans-11/tgoskits", branch = "axvisor-core", features = ["custom-base"] }
axvisor_api = { git = "https://github.com/Ivans-11/tgoskits", branch = "axvisor-core", default-features = false }
axvisor_core = { git = "https://github.com/Ivans-11/tgoskits", branch = "axvisor-core", default-features = false }
ostd.workspace = true
spin.workspace = true

[lints]
workspace = true
