[package]
name = "axvisorctl"
version = "0.17.2"
edition = "2024"
description = "Asterinas Axvisor host tooling"
license = "MPL-2.0"
repository = "https://github.com/asterinas/asterinas"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.47", features = ["derive"] }
flate2 = "1.1.2"
libc = "0.2.177"
regex = "1.11.2"
reqwest = { version = "0.12.23", default-features = false, features = ["blocking", "rustls-tls"] }
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10.9"
tar = "0.4.44"
toml = "0.8.23"
xz2 = "0.1.7"
